### ISSUE TITLE
章节正文的最后一个字符被误删了

### ISSUE THREAD

**Issue by Fire-Marshall** [SeaLoong/HbookerAppNovelDownloader#1]
程序很好用，非常感谢😀，不过所有章节的正文的最后一个字符都被吞了，看了一下，应该是这里出错了：
https://github.com/SeaLoong/HbookerAppNovelDownloader/blob/15f5ab0666c1cf1f0d0145ae958e776a7d01ff11/book.py#L158

这一行应该改成：
`content = content[:-1]`

**Comment by SeaLoong** [comment]
惊了，竟然会有人用。不过这个东西我这因为一些原因暂时没法正常运行，也没法调试，而且也不怎么需要维护了。这个以后直接发PR就行了。
